### PR TITLE
add Api end points

### PR DESCRIPTION
**Pull request by Alzubair98**
all requirements are done 

- Create an API endpoint to list all posts for a user.
- Create an API endpoint to list all comments for a user's post.
- Add authentication to your API endpoints.
- Your API endpoints should receive JSON and respond JSON as well.

### CODE REVIEW

**Comment by Alzubair98** [comment]
IM DOING THIS ALONE BECAUSE MY TEAM MATE LEFT MICROVERSE FOR THIS WEEK 
quit

**Comment by Alzubair98** [comment]
TO CHECK THE API (YOU CAN ALSO USE POSTMAN FOR EASY API USE)
run http://[127.0.0.1:3000/api/v1/posts](http://127.0.0.1:3000/api/v1/posts) 
to see all posts in JSON format 
for the comments on a specific post  run this 
http://[127.0.0.1:3000/api/v1/posts/post_id](http://127.0.0.1:3000/api/v1/posts/post_id)

PLEASE DONT FORGET TO CONFRIM YOUR EMAIL WHEN YOU SIGN UP TO THE BLOG APP

**Review by omar-muhamad — COMMENTED** [review]
# Invalid ❌

Hi @Alzubair98 and @williamscch,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [ ] Some linters checks are not passed. Please make sure that all checks are passing and green.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by omar-muhamad** [comment]
Hi @Alzubair98 and @williamscch,
After you ask for a review to your project,
Kindly don't push any changes until you get the review from the code reviewer.
Have a great day 😊

**Review by Mihndim2020 — APPROVED** [review]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
### Hi @Alzubair98, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark:  Clean and Organized code
:heavy_check_mark: Descriptive Readme file

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

Congratulations-Memes-FEATURED

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
