### PR TITLE
Add authorization rules

### PR DESCRIPTION
**Pull request by Alzubair98**
All requirements are done

- Install CanCanCan in your project.
- Add a role column to the users table. Remember to use a migration for this.
- A user can delete a post if it is theirs or if they have an admin role (column role has value "admin"). Use CanCanCan for this authorization.
- For that you need to implement the post deleting functionality. Add the "Delete" button to the view and make sure that only authorized users can see it.
- A user can delete a comment if it is theirs or if they have an admin role (column role has value "admin"). Use CanCanCan for this authorization.
- For that you need to implement the comment deleting functionality. Add the "Delete" button to the view and make sure that only authorized users can see it.

### CODE REVIEW

**Comment by Alzubair98** [comment]
IM DOING EVERYTHING ALONE BECAUSE MY TEAM MATE JUST LEFT MICROVERSE FOR THIS WEEK

quit

**Review by andersonlebon — CHANGES_REQUESTED** [review]
### Hi @Alzubair98 

## Required Changes ♻️

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

almost-there
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

- [x] First, sorry for your coding partner. I know you worked so hard :1st_place_medal: Please there is an issue you can fix.
Annotation 2022-11-04 025220
Annotation 2022-11-04 02220

- When we are trying to signup, we are getting an error message. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

**Comment by Alzubair98** [comment]
@andersonlebon  hello Anderson Lebon 
i think you trying to user the same email more than one time that's why its show that error

**Comment by Alzubair98** [comment]
https://www.loom.com/share/26f2bce0556a4ea8aee46712b6c65f4d

here is an explanation of the code 
and its working good 
the problem is the code reviewer used the same email tow times 
so that will throw and error because of the unique validation

**Comment by andersonlebon** [comment]
Hello @Alzubair98
Thank you for your video explanation :smiley: 
Yes, I saw the error, and sorry about that. :+1: 
After signing up, I was not getting any massage or a directory path. so when I clicked on the button two times or three times, now I was getting that error message.
Create a new pull request so that we can review the rest of the project :+1: 

Cheers and Happy coding! :clap: :clap: :clap: 

Thank you :smile:

**Comment by arslanbisharat** [comment]
Hi @Alzubair98,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
